version: '3.8'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo_v2
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - mongo_data_v2:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: health-server
    restart: unless-stopped
    ports:
      - "5500:5500"
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: health-client
    restart: unless-stopped
    ports:
      - "3100:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data_v2:
